# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guide.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(179, 179, 179);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 0, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 511, 181))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 481, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 340, 601, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Guide"))
        self.label.setText(_translate("MainWindow", "Guide"))
        self.label_2.setText(_translate("MainWindow", "1. Menu Stock Data \n"
                                        "a. Berfungsi menampilkan data saham LQ45\n"
                                        "b. Cara menggunakan : Masukan kode saham LQ45, Lalu klik show\n"
                                        "c. Ket : \n"
                                        "- Market Cap : Kapitalisasi Pasar\n"
                                        "- PE : Rasio laba untung/rugi\n"
                                        "- Beta: Rasio Harga saham terhadap IHSG"))
        self.label_3.setText(_translate("MainWindow", "2. Menu Cluster stock\n"
                                        " a.Befungsi Mengelompokan saham kedalam kelompok tertentu\n"
                                        " b.Menggunakan metode K-Medoids\n"
                                        " c. Cara pemakai : Klik tombol cluster "))
        self.label_4.setText(_translate("MainWindow", "3. Menu Rank Stock\n"
                                        " a. Berfungsi melakukan pengurutans saham \n"
                                        " b. Cara pemakaian : Masukan bobot pada indikator yang tersedia, lalu klik rank \n"
                                        " c. Hasil ranking akan muncul pada kotak cluster, dimana saham pada posisi teratas merupakan saham yang cocok dengan inputan user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
